# -*- coding: utf-8 -*-
"""Wandb Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yS56uX-XILbdkrKPT4ywA6CrzqqvkC34
"""

!pip install langchain==0.0.350 openai faiss-gpu tiktoken
!pip install wandb

import os
from google.colab import userdata
os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

os.environ["LANGCHAIN_WANDB_TRACING"] = "true"

!pip install pypdf

from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

# Chunking
loader = PyPDFLoader("CommonInsuranceTerms.pdf")

documents = loader.load()
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500,chunk_overlap=50)
texts = text_splitter.split_documents(documents)

texts[0]

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores.faiss import FAISS

docsearch = FAISS.from_documents(texts, OpenAIEmbeddings())

docsearch.save_local("/content")

from langchain.chains import RetrievalQA
from langchain.llms import OpenAI

qa_chain = RetrievalQA.from_chain_type(
    llm=OpenAI(temperature=0.3),
    chain_type="stuff",
    retriever=docsearch.as_retriever(),
)

print(qa_chain.run("What is Mortality Charge?"))

print(qa_chain.run("Tell me about Preferred provider organization (PPO)."))

